"""Initial migration.

Revision ID: 8da060ae1e83
Revises: 
Create Date: 2025-04-27 18:02:15.488357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da060ae1e83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('engine_capacity', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('frame_number', sa.String(length=50), nullable=True),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('stnk_expiry_date', sa.Date(), nullable=True),
    sa.Column('bpkb_status', sa.String(length=50), nullable=True),
    sa.Column('buy_price', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('discount_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_to', sa.String(length=100), nullable=True),
    sa.Column('acquisition_source', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_photo_url', sa.String(length=255), nullable=True),
    sa.Column('inspection_passed', sa.Boolean(), nullable=True),
    sa.Column('warranty', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('motors')
    op.drop_table('tenants')
    # ### end Alembic commands ###
